
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=aloc
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
    driver: local