spring:
  profiles:
    active: dev

# dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aloc
    username: postgres
    password: password
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            show_sql: true
            format_sql: true
            default_batch_fetch_size: 500


